### PR TITLE
Rendering test fix

### PR DESCRIPTION
**Pull request by dkuntze**
Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Review by tripodsan — COMMENTED** [review]
seems to be a node-version difference. the tests pass on node 20

**Comment by tripodsan** [comment]
@dkuntze please create a PR directly on a branch on this repo, so that the CI tests run.

**Comment by dkuntze** [comment]
@tripodsan it does look like a node version difference. I'll close this.

**Comment by dkuntze** [comment]
not needed for node v20

**Pull request closed without merging**
