### PR TITLE
fix: add required og:type to metadata

### LINKED ISSUE #685: Metadata missing required og:type
**Description**

OG protocol requires the `og:type`, e.g. `<meta property="og:type" content="video.movie" />` [1]

**Expected behavior**

Any OG tags in meta should include `og:type`.

In [2] consider:

```js
  'og:type': meta['og:type'] || 'website',
```

The indirect default is "website" [3]:

> Any non-marked up webpage should be treated as og:type website

"article" is valid in many cases.

**Related**

AEM may want to consider generalizing a default "type" meta as there is overlap with other metadata like JSON-LD. For example, they both have 'website' and 'article' in common.

Twitter uses OG properties so pipeline duplicating some props by default may be redundant [4] 

**References**

1. https://ogp.me/#metadata
2. https://github.com/adobe/helix-html-pipeline/blob/7959603df0d19b75b7fe2abea662b48c1dc504f8/src/steps/extract-metadata.js#L268
3. https://ogp.me/#no_vertical
4. https://developer.x.com/en/docs/x-for-websites/cards/overview/markup

### PR DESCRIPTION
**Pull request by hparra**
Please ensure your pull request adheres to the following guidelines:

- [x] make sure to link the related issues in this description
- [x] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Fixes #685

Thanks for contributing!

### CODE REVIEW

**Comment by hparra** [comment]
`npm test` passed locally. not sure why ci is not running here.

**Review by tripodsan — CHANGES_REQUESTED** [review]
- please revert the changes in `.github/workflows/main.yaml` they are unrelated to the issue
- we need to discuss this first in an issue, why adding `og:type` is needed.

**Comment by hparra** [comment]
> * please revert the changes in `.github/workflows/main.yaml` they are unrelated to the issue

@tripodsan https://github.com/adobe/helix-html-pipeline/pull/687

**Comment by tripodsan** [comment]
won't fix.

**Pull request closed without merging**
